<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_islandora_oai_identify_request_handler().
 *
 * This custom request handler reuses all of the requests defined in
 * islandora_oai_islandora_oai_identify_request_handler() other than
 * 'response_xml'.
 */
function islandora_oai_cmdi_islandora_oai_identify_request_handler() {
  return array(
    'islandora_oai_cmdi' => array(
      'label' => t('Islandora OAI for CMDI and OLAC metadata'),
      'description' => t("Request handler for CMDI and OLAC metadata datastreams."),
      'configuration' => 'admin/islandora/tools/islandora-oai/handler',
      'requests' => array(
        'ListIdentifiers' => array(
          'file' => drupal_get_path('module', 'islandora_oai') . '/includes/handler.inc',
          'function' => 'islandora_oai_retrieve_records_or_identifiers',
        ),
        'ListRecords' => array(
          'file' => drupal_get_path('module', 'islandora_oai') . '/includes/handler.inc',
          'function' => 'islandora_oai_retrieve_records_or_identifiers',
        ),
        'ListSets' => array(
          'file' => drupal_get_path('module', 'islandora_oai') . '/includes/handler.inc',
          'function' => 'islandora_oai_retrieve_sets',
        ),
        'GetRecord' => array(
          'file' => drupal_get_path('module', 'islandora_oai') . '/includes/handler.inc',
          'function' => 'islandora_oai_retrieve_record',
        ),
        'response_xml' => array(
          'file' => drupal_get_path('module', 'islandora_oai') . '/includes/handler.inc',
          'function' => 'islandora_oai_object_response_xml',
        ),
        'set_membership' => array(
          'file' => drupal_get_path('module', 'islandora_oai') . '/includes/handler.inc',
          'function' => 'islandora_oai_get_membership',
        ),
      ),
    ),
  );
}
